tasks:
#  - init: 'echo "TODO: Replace with init/build command"'
#    command: 'echo "TODO: Replace with command to start project"'
  - init: pip install --upgrade pip
  - init: pip3 install -r requirements.txt


    #command: python3 /Code/HMM.py